default:
  image: 799170964164.dkr.ecr.eu-west-2.amazonaws.com/turing:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_FORCE_HTTPS: "true"

stages:
  - build

build-job:
  tags:
    - docker
  stage: build
  before_script:
  - git remote prune origin  # Remove stale remote branches
  - git fetch --prune --all  # Fetch fresh refs, removing old ones
  - git branch -r            # List remote branches for verification
  - mkdir -p $HOME/.ssh
  - echo "HOST *" > ~/.ssh/config
  - echo "StrictHostKeyChecking no" >> ~/.ssh/config
  script:
    - date
    - source /turing/setup.sh
    - date
    - make -j4
    - date
    - make test
    - date
  artifacts:
    when: always
    paths:
      - unit_tests.xml
    reports:
      junit: unit_tests.xml
