name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
            # Fetch submodules using the built-in token over HTTPS
            submodules: true
            # Ensure credentials are set for submodule fetches
            persist-credentials: true
    - name: Configure cmake
      shell: bash
      run: mkdir -p ${{ github.workspace }}/build && cd ${{ github.workspace }}/build && cmake ..
    - name: Build
      shell: bash
      run: cd ${{ github.workspace }}/build && make
