name: CI macos-arm

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest-xlarge

    steps:
    - uses: actions/checkout@v4
      with:
            # Fetch submodules using the built-in token over HTTPS
            submodules: recursive
            # Ensure credentials are set for submodule fetches
            persist-credentials: true
    - name: Check if macOS ARM
      run: |
        if [[ "$(uname -m)" == "arm64" ]]; then
          echo "Platform is macOS ARM"
        else
          echo "Platform is not macOS ARM ($(uname -m))"
          exit 1
        fi
    - name: Install LLVM and recent clang
      run: brew install llvm -q 
    - name: Install dependencies
      run: ./dependencies.sh
    - name: Configure cmake
      shell: bash
      run: mkdir -p ${{ github.workspace }}/build && cd ${{ github.workspace }}/build && CC=/opt/homebrew/opt/llvm/bin/clang CXX=/opt/homebrew/opt/llvm/bin/clang++ cmake ..
    - name: Build
      shell: bash
      run: cd ${{ github.workspace }}/build && make
